buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        maven { url = 'https://maven.minecraftforge.net' }
        jcenter()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'java'

version = '1.0.0'
group   = 'dev.wraith'
archivesBaseName = 'WraithMod-Forge-189'

minecraft {
    version  = '1.8.9-11.15.1.2318-1.8.9'
    runDir   = 'run'
    mappings = 'stable_20'
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

task copyToLauncher(type: Copy, dependsOn: reobfJar) {
    from(jar.outputs.files)
    into '../publish'
    rename { 'WraithMod-Forge.jar' }
}
build.finalizedBy copyToLauncher
