buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        maven { url = 'https://maven.minecraftforge.net' }
        jcenter()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'java'

version = '1.0.0'
group   = 'dev.wraith'
archivesBaseName = 'WraithMod-Forge'

minecraft {
    version  = '1.12.2-14.23.5.2847'
    runDir   = 'run'
    mappings = 'stable_39'
}

repositories {}
dependencies {}

jar {
    manifest.attributes(
        'FMLCorePlugin'            : '',
        'FMLCorePluginContainsFMLMod': 'true',
        'FMLAT'                    : ''
    )
}

task copyToLauncher(type: Copy, dependsOn: reobfJar) {
    from(jar.outputs.files)
    into '../publish'
    rename { 'WraithMod-Forge.jar' }
}
build.finalizedBy copyToLauncher

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8
